name: GH Act Test
run-name: ${{ github.actor }} is testing GH Act
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The step was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This step is now running on a ${{ runner.os }} server hoste by GitHub."
      - run: echo "The name of your branch is ${{ github.ref }} and your repo is ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner"
      - run: echo "List files in the repository"
      - run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}"